In [6]:
import tensorflow as tf
from pprint import pprint

In [7]:
input_ids = tf.constant([ # [batch_size, seq_length, input_nums]
    [[101, 1], [102, 2], [0, 0], [0, 0]],
    [[101, 3], [102, 4], [103, 5], [0, 0]]
])
flat_input_ids = tf.reshape(input_ids, [-1])
pprint(flat_input_ids)

<tf.Tensor: shape=(16,), dtype=int32, numpy=
array([101,   1, 102,   2,   0,   0,   0,   0, 101,   3, 102,   4, 103,
         5,   0,   0], dtype=int32)>


In [11]:
one_hot_input_ids = tf.one_hot(flat_input_ids, depth=1024)
pprint(one_hot_input_ids)
print(one_hot_input_ids.shape)

<tf.Tensor: shape=(16, 1024), dtype=float32, numpy=
array([[0., 0., 0., ..., 0., 0., 0.],
       [0., 1., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [1., 0., 0., ..., 0., 0., 0.],
       [1., 0., 0., ..., 0., 0., 0.]], dtype=float32)>
(16, 1024)


In [18]:
from math_tool import reshape_to_matrix
import tensorflow as tf

A = tf.constant([ # [batch_size, seq_length, input_nums]
    [[1, 2], [3, 4], [5, 6]],
    [[7, 8], [9, 10], [11, 12]]
])
pprint(A)
print(A.shape)
matrix_A = reshape_to_matrix(A)
pprint(matrix_A)
print(matrix_A.shape)

<tf.Tensor: shape=(2, 3, 2), dtype=int32, numpy=
array([[[ 1,  2],
        [ 3,  4],
        [ 5,  6]],

       [[ 7,  8],
        [ 9, 10],
        [11, 12]]], dtype=int32)>
(2, 3, 2)
<tf.Tensor: shape=(6, 2), dtype=int32, numpy=
array([[ 1,  2],
       [ 3,  4],
       [ 5,  6],
       [ 7,  8],
       [ 9, 10],
       [11, 12]], dtype=int32)>
(6, 2)
